### PR TITLE
Use latest Passport version

### PR DESCRIPTION
**Pull request by flefloch-payps**

### CODE REVIEW

**Review by tonyputi — CHANGES_REQUESTED** [review]
Please check and confirm that passport version 7.0 is working on lumen 5.5
I'll make branches for lumen 5.6 and 5.7 with correct package version to make it similar to laravel.

**Review by tonyputi — CHANGES_REQUESTED** [review]
I can't merge this sorry. The name of package and everything from my repository must have nomadnt

**Comment by flefloch-payps** [comment]
I confirm that I'm using it with Lumen 5.7.7 and everything is working fine, but I can't tell for 5.5.
I changed the repo name to be able to deploy from gitLab,  I changed it back. Do you need me to make a new merge request (sorry not really familiar with the process)?

**Comment by purwadarozatun** [comment]
@tonyputi can you merge this . ?

**Comment by purwadarozatun** [comment]
Hello @tonyputi i find this merge request is useful . can you merge this ?

**Comment by purwadarozatun** [comment]
@fleflochN   maybe @tonyputi suggest to change all change except passport version

**Comment by flefloch-payps** [comment]
Hey guys, I think I already did it.
If I'm not mistaking I have reverted the package name to nomadt.
@tonyputi Can you confirm that everything is OK from your side?

Thank you.

**Comment by purwadarozatun** [comment]
i think this line is the last 

 "homepage": "https://github.com/fleflochN/lumen-passport",

**Comment by flefloch-payps** [comment]
Oh F*** you're right I missed that one.
@tonyputi I've sent a new pull request. Let me know if this one is OK for you.

**Pull request closed without merging**
